# Generated by Django 4.0.3 on 2022-03-17 12:37

from django.db import migrations
from django.db import connection
import os

def make_trigger(apps, schema_editor):
    sql_data = ""
    file_path = os.path.join(os.path.dirname(__file__), "mtaa_db.sql")

    with open(file_path, "r") as sql_file:
        sql_data = sql_file.read()
 
    with connection.cursor() as cursor:
        cursor.execute(sql_data)

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(make_trigger)
    ]
